chore: support Qt6&DTK6
linuxdeepin/dtknotifications pull request #5
Opened 2023-06-27 09:10 UTC by xzl01

Log:

2023-06-27 09:13 UTC, asterwyx requested changes

2023-06-27 09:13 UTC, asterwyx commented on CMakeLists.txt
> +set(DTK_VERSION "5.0.0" CACHE STRING "define project version")
这个不应该升到5.0.0

2023-06-27 09:15 UTC, xzl01 commented on CMakeLists.txt
> +set(DTK_VERSION "5.0.0" CACHE STRING "define project version")
systemsetting的也改为5.0了，如果这个不改的话 那那个也得改回来

2023-07-06 02:08 UTC, asterwyx requested changes

2023-07-06 02:08 UTC, asterwyx commented on CMakeLists.txt
> +message(${QT_VERSION_MAJOR})
这一个打印删除掉，或者换成更有意义的打印。

2023-07-06 02:56 UTC, asterwyx approved these changes

2023-07-06 04:40 UTC, merged